### ISSUE TITLE
Circular dependency between Sequence and AsSequence

### ISSUE THREAD

**Issue by jpsullivan** [pineapplemachine/higher#40]
I'm doing some testing over here and noticed that webpack is throwing errors in `asSequence.js` on this line:

```javascript
export const ArraySequence = Sequence.extend({
```

I dug around and this is because Sequence and asSequence both depend on each other. Commenting out `import {ArraySequence} from "./asSequence";` in `sequence.js` clears the error, but surely causes other problems.

**Comment by pineapplemachine** [comment]
This could be fixed by moving `forceEager` out of `sequence.js`, or by rewriting it to not depend on `ArraySequence`. (Moving it is probably better.)

**Comment by jpsullivan** [comment]
Fixed in #48
